const forms = [
    {
        Page: 1,
        Des: "hellow welcome to page 1",
        fields: [{ type: 'text', label: 'Name' },
        { type: 'text', label: 'Field 2' },
        { type: 'text', label: 'Field 3' },
        { type: 'text', label: 'Field 4' },
        { type: 'text', label: 'Field 5' },
        { type: 'text', label: 'Field 6' },
        { type: 'text', label: 'Field 7' },
        { type: 'text', label: 'Field 8' },
        { type: 'text', label: 'Field 9' },
        {
            type: 'Dropdown',
            label: 'Select State', // Changed label
            options: [
                { label: "Andhra Pradesh", value: "Andhra Pradesh" },
                { label: "Arunachal Pradesh", value: "Arunachal Pradesh" },
                { label: "Assam", value: "Assam" },
                { label: "Bihar", value: "Bihar" },
                { label: "Chhattisgarh", value: "Chhattisgarh" },
                { label: "Goa", value: "Goa" },
                { label: "Gujarat", value: "Gujarat" },
                { label: "Haryana", value: "Haryana" },
                { label: "Himachal Pradesh", value: "Himachal Pradesh" },
                { label: "Jharkhand", value: "Jharkhand" },
                { label: "Karnataka", value: "Karnataka" },
                { label: "Kerala", value: "Kerala" },
                { label: "Madhya Pradesh", value: "Madhya Pradesh" },
                { label: "Maharashtra", value: "Maharashtra" },
                { label: "Manipur", value: "Manipur" },
                { label: "Meghalaya", value: "Meghalaya" },
                { label: "Mizoram", value: "Mizoram" },
                { label: "Nagaland", value: "Nagaland" },
                { label: "Odisha", value: "Odisha" },
                { label: "Punjab", value: "Punjab" },
                { label: "Rajasthan", value: "Rajasthan" },
                { label: "Sikkim", value: "Sikkim" },
                { label: "Tamil Nadu", value: "Tamil Nadu" },
                { label: "Telangana", value: "Telangana" },
                { label: "Tripura", value: "Tripura" },
                { label: "Uttar Pradesh", value: "Uttar Pradesh" },
                { label: "Uttarakhand", value: "Uttarakhand" },
                { label: "West Bengal", value: "West Bengal" },
                // Union territories
                { label: "Andaman and Nicobar Islands", value: "Andaman and Nicobar Islands" },
                { label: "Chandigarh", value: "Chandigarh" },
                { label: "Dadra and Nagar Haveli and Daman and Diu", value: "Dadra and Nagar Haveli and Daman and Diu" },
                { label: "The Government of NCT of Delhi", value: "The Government of NCT of Delhi" },
                { label: "Jammu and Kashmir", value: "Jammu and Kashmir" },
                { label: "Ladakh", value: "Ladakh" },
                { label: "Lakshadweep", value: "Lakshadweep" },
                { label: "Puducherry", value: "Puducherry" },
            ]
        }
        ]
    },
    {
        Page: 2,
        Des: "Personal Deatils \nEnter Your Personel Details",
        fields: [{ type: 'text', label: 'Jee Main Application Number' },
        { type: 'text', label: 'Institute Name' },
        { type: 'text', label: 'First Name' },
        { type: 'text', label: 'Middle Name' },
        { type: 'text', label: 'Last Name' },
        { type: 'text', label: 'Email' },
        { type: 'text', label: 'Contact Number' },
        {
            type: 'dropdown', label: 'Category',
            options: [
                { label: "SC", value: "SC" },
                { label: "ST", value: "ST" },
                { label: "Gen", value: "Gen" },
                { label: "OBC", value: "OBC" },
            ]
        },
        { type: 'text', label: 'Allocated Category' },
        { type: 'text', label: 'Country' },
        {
            type: 'dropdown',
            label: 'Select State', // Changed label
            options: [
                { label: "Andhra Pradesh", value: "Andhra Pradesh" },
                { label: "Arunachal Pradesh", value: "Arunachal Pradesh" },
                { label: "Assam", value: "Assam" },
                { label: "Bihar", value: "Bihar" },
                { label: "Chhattisgarh", value: "Chhattisgarh" },
                { label: "Goa", value: "Goa" },
                { label: "Gujarat", value: "Gujarat" },
                { label: "Haryana", value: "Haryana" },
                { label: "Himachal Pradesh", value: "Himachal Pradesh" },
                { label: "Jharkhand", value: "Jharkhand" },
                { label: "Karnataka", value: "Karnataka" },
                { label: "Kerala", value: "Kerala" },
                { label: "Madhya Pradesh", value: "Madhya Pradesh" },
                { label: "Maharashtra", value: "Maharashtra" },
                { label: "Manipur", value: "Manipur" },
                { label: "Meghalaya", value: "Meghalaya" },
                { label: "Mizoram", value: "Mizoram" },
                { label: "Nagaland", value: "Nagaland" },
                { label: "Odisha", value: "Odisha" },
                { label: "Punjab", value: "Punjab" },
                { label: "Rajasthan", value: "Rajasthan" },
                { label: "Sikkim", value: "Sikkim" },
                { label: "Tamil Nadu", value: "Tamil Nadu" },
                { label: "Telangana", value: "Telangana" },
                { label: "Tripura", value: "Tripura" },
                { label: "Uttar Pradesh", value: "Uttar Pradesh" },
                { label: "Uttarakhand", value: "Uttarakhand" },
                { label: "West Bengal", value: "West Bengal" },
                // Union territories
                { label: "Andaman and Nicobar Islands", value: "Andaman and Nicobar Islands" },
                { label: "Chandigarh", value: "Chandigarh" },
                { label: "Dadra and Nagar Haveli and Daman and Diu", value: "Dadra and Nagar Haveli and Daman and Diu" },
                { label: "The Government of NCT of Delhi", value: "The Government of NCT of Delhi" },
                { label: "Jammu and Kashmir", value: "Jammu and Kashmir" },
                { label: "Ladakh", value: "Ladakh" },
                { label: "Lakshadweep", value: "Lakshadweep" },
                { label: "Puducherry", value: "Puducherry" },
            ]
        },
        { type: 'text', label: 'City' },
        { type: 'text', label: 'Pincode' },
        { type: 'text', label: 'Permanent Address 1' },
        { type: 'text', label: 'Permanent Address 2' },
        {
            type: 'dropdown', label: 'Blood Group',
            options: [
                { label: "AB+", value: "AB+" },
                { label: "A+", value: "A+" },
                { label: "B+", value: "B+" },
                { label: "O+", value: "O+" },
                { label: "AB-", value: "AB-" },
                { label: "A-", value: "A-" },
                { label: "B-", value: "B-" },
                { label: "O-", value: "O-" },
            ]
        },
        { type: 'text', label: 'Nationality' },
        {
            type: 'dropdown', label: 'Religion',
            options: [
                { label: "Hindu", value: "Hindu" },
                { label: "Muslim", value: "MuslChristian" },
                { label: "Christian", value: "Christian" },
                { label: "Shikh", value: "Shikh" },
            ]
        },
        { type: 'text', label: 'Birthplace' },
        { type: 'file', label: 'Upload Photo' },
        { type: 'file', label: 'Upload Signature' },
        ]
    },
    {
        Page: 3,
        Des: "*Hostel Info Form*",
        fields: [{ type: 'text', label: 'Name' },
        { type: 'text', label: 'Admission No.' },
        { type: 'text', label: 'Laptop Make' },
        { type: 'text', label: 'Laptop Model' },
        { type: 'text', label: 'Laptop Serrial No.' },
        { type: 'text', label: 'Field 6' },
        ]
    },
    {
        Page: 4,
        Des: "*IIT ISM Email*\nInstitute Email Registration Details ",
        fields: [{ type: 'text', label: 'password', require: true },
        { type: 'text', label: 'Admission No.' },
        { type: 'text', label: 'First Name' },
        { type: 'text', label: 'Middle Name' },
        { type: 'text', label: 'Last Name' },
        { type: 'text', label: 'Present Email' },
        { type: 'text', label: 'Year Of Admission' },
        { type: 'text', label: 'Year Of Passing' },
        { type: 'text', label: 'Course' },
        { type: 'text', label: 'Branch' },
        {
            type: 'Dropdown',
            label: 'Select State', // Changed label
            options: [
                { label: "Andhra Pradesh", value: "Andhra Pradesh" },
                { label: "Arunachal Pradesh", value: "Arunachal Pradesh" },
                { label: "Assam", value: "Assam" },
                { label: "Bihar", value: "Bihar" },
                { label: "Chhattisgarh", value: "Chhattisgarh" },
                { label: "Goa", value: "Goa" },
                { label: "Gujarat", value: "Gujarat" },
                { label: "Haryana", value: "Haryana" },
                { label: "Himachal Pradesh", value: "Himachal Pradesh" },
                { label: "Jharkhand", value: "Jharkhand" },
                { label: "Karnataka", value: "Karnataka" },
                { label: "Kerala", value: "Kerala" },
                { label: "Madhya Pradesh", value: "Madhya Pradesh" },
                { label: "Maharashtra", value: "Maharashtra" },
                { label: "Manipur", value: "Manipur" },
                { label: "Meghalaya", value: "Meghalaya" },
                { label: "Mizoram", value: "Mizoram" },
                { label: "Nagaland", value: "Nagaland" },
                { label: "Odisha", value: "Odisha" },
                { label: "Punjab", value: "Punjab" },
                { label: "Rajasthan", value: "Rajasthan" },
                { label: "Sikkim", value: "Sikkim" },
                { label: "Tamil Nadu", value: "Tamil Nadu" },
                { label: "Telangana", value: "Telangana" },
                { label: "Tripura", value: "Tripura" },
                { label: "Uttar Pradesh", value: "Uttar Pradesh" },
                { label: "Uttarakhand", value: "Uttarakhand" },
                { label: "West Bengal", value: "West Bengal" },
                // Union territories
                { label: "Andaman and Nicobar Islands", value: "Andaman and Nicobar Islands" },
                { label: "Chandigarh", value: "Chandigarh" },
                { label: "Dadra and Nagar Haveli and Daman and Diu", value: "Dadra and Nagar Haveli and Daman and Diu" },
                { label: "The Government of NCT of Delhi", value: "The Government of NCT of Delhi" },
                { label: "Jammu and Kashmir", value: "Jammu and Kashmir" },
                { label: "Ladakh", value: "Ladakh" },
                { label: "Lakshadweep", value: "Lakshadweep" },
                { label: "Puducherry", value: "Puducherry" },
            ]
        }]
    },

]



export default forms